package-lock.json, package.json, src/components/SignInForm.jsx, src/components/authService.jsx, src/components/config.json, src/components/httpService.jsx, src/components/logService.jsx
Marty, if you see anything that should not be in code review please let me know.
=> Sign in form

src/components/AdditionalInformation.jsx
Marty, Let me know if you see anything that should not be included with this PR.
=> Additional information form

src/App.js, src/components/AdditionalInformation.jsx, src/components/CustomErrorHandling.jsx, src/components/ResetPassword.jsx, src/components/SignInForm.jsx, src/components/SignUpForm.jsx, src/components/authService.jsx, src/components/config.json, src/components/httpService.jsx, src/components/logService.jsx, src/serviceWorker.js
Added the connections to the end points. Login, sign up and password reset, have all been incorporated and tested.
=> Connect end points

src/App.js, src/components/AdditionalInformation.jsx, src/components/AutocompleteTypeField.jsx, src/components/Collaspe.jsx, src/components/FormContainer.jsx, src/components/GetReport.jsx, src/components/ProvideDetails.jsx, src/components/RequestSubTypeField.jsx, src/components/ResetPassword.jsx, src/components/ServiceRequestForm.jsx, src/components/SignInForm.jsx, src/components/SignUpForm.jsx, src/components/SubmitResponsePage.jsx, src/components/checkFormCompletion.js, src/components/config.js, src/components/fieldContent.json, src/components/map.jsx, src/components/map1.jsx, src/components/returnEnvironmentItems.js, src/components/withFormik.jsx
Fixed various git hub issues and added the ability to customize all label content on forms through a json file.
=> Added json file label population and fixed requiresLocation paramater

src/components/config.js, src/components/returnEnvironmentItems.js
Adds a config item, so that the map points to the local dev environment, when running the app locally
=> added local development environment

package-lock.json, package.json, src/components/SignUpForm.jsx
Changed validation logic to use https://www.npmjs.com/package/@baltimorecounty/validation.
addresses #44
=> Fix phone number validation

src/components/ServiceRequestForm.jsx, src/components/animalBreedType.jsx, src/components/animalColorType.jsx, src/components/otherAnimalTypes.jsx, src/components/petType.jsx, src/components/requestCategory.jsx, src/components/requestSubCategory.jsx, src/components/serviceDescription.jsx, src/components/sexType.jsx
Sanjay and I Broke out all the combo boxes into components. Makes the service request form more readable.
=> Clean up clean up everbody everywhere

package-lock.json, package.json, src/components/ProvideDetails.jsx, src/components/SeButton.jsx, src/components/SignInForm.jsx, src/components/SignUpForm.jsx
Added a component which will allow for loading indicators in buttons `SeButton` which attempts to utilize se styles.
=> Add loading indicators

src/components/FormContainer.jsx, src/components/ProvideDetails.jsx, src/components/SeButton.jsx, src/components/SignUpForm.jsx
=> Added missing text to Sign Up Form

src/App.js, src/Routing.jsx, src/components/AdditionalInformation.jsx, src/components/GetReport.jsx, src/components/ProvideDetails.jsx, src/components/ResetPasswordForm.jsx, src/components/ServiceRequestForm.jsx, src/components/SignInForm.jsx, src/components/SignUpForm.jsx, src/components/SubmitResponsePage.jsx, src/components/submitReport.js
Addresses #60 
- Created Routing File
- Added routes to replace static string routes
- Moved Router to Routing File
- Added shortcuts for navigation
=> Consolidate routing

src/components/IssueType.jsx, src/components/ProvideDetails.jsx
Addresses #61
Changes key to add lat and long which should be unique.
=> Fix autocomplete key

src/utilities/config.js
=> fixed bad reference

src/components/AutocompleteTypeField.jsx, src/components/describeTheProblem.jsx
=> Max length describe the problem#89

public/data/form-field-names.json
Modified to Provide Details in form-field-names.json to display correct text on the Tab(Progress bar).
=> Modified 'Enter a Location" to Provide Details#71

src/components/AdditionalInformation.jsx
Fixed Issue with Enter key on a field taking it back to previous page.
=> Enter key issue with additional information#94

src/components/ServiceRequestForm.jsx
Addresses #91 
Added categories to the shared formik props for use on the provide details tab.
=> Describe the Problem - Only show validation when touched and has error message

src/components/animalBreedType.jsx, src/components/animalColorType.jsx, src/components/otherAnimalTypes.jsx, src/components/petType.jsx, src/components/requestCategory.jsx, src/components/requestSubCategory.jsx, src/components/sexType.jsx
=> fixed spacing in select issues

src/components/SignUpForm.jsx
Addresses #76
Since the message comes from Citysourced, we handling it here manually. However, this is a bit hacky and at the submit will of Citysourced so this should be moved to the api, and hopefully a bit be a bit more flexible.
@tmccoy529 are we tracking any work items for the api?
=> Handle already existing account

src/components/Collaspe.jsx, src/components/map.jsx
Addresses #69 
- Removed card component, seems to be causing the margin issue
- Modified height to be the same for the map and the container
=> Troubleshoot map size issues

src/components/ServiceRequestForm.jsx, src/utilities/FormHelpers.js
=> fixed naming issue

src/components/ProvideDetails.jsx, src/components/ServiceRequestForm.jsx, src/components/animalBreedType.jsx, src/components/animalColorType.jsx, src/components/otherAnimalTypes.jsx, src/components/petType.jsx, src/components/sexType.jsx
Use the category flag instead of checking the category text. Will create an issue to match up on this.
=> Animal services Category Flag

src/components/AdditionalInformation.jsx, src/components/ProvideDetails.jsx, src/components/ServiceRequestForm.jsx, src/components/withFormik.jsx, src/utilities/FormHelpers.js, src/utilities/FormikHelpers.js
Addresses #18 
Ensures active category exists
=> Hf isanimal

src/components/AdditionalInformation.jsx, src/components/ProvideDetails.jsx, src/components/withFormik.jsx, src/utilities/FormHelpers.js, src/utilities/FormikHelpers.js
Addresse #116 
Additional Info Form was not validating
We probably want to look at the form validation as a whole, but attempted to make minimal changes to get this to work.
=> Additional info form fixes

src/components/Note.jsx, src/components/SignInForm.jsx
Added ability to customize the css classes for Note and changed the reset password to use Note instead of Alert.
=> Fixed CSS for success message alert.

src/components/AdditionalInformation.jsx, src/components/SignInForm.jsx
Fixed the password reset styling issue and addressed #116
=> Update alert css

src/components/Note.jsx, src/components/SignInForm.jsx
This addresses #68. An alert message will pop up at the top now when the username and password doesn't match.
=> Add alert for sign in

src/components/ServiceRequestForm.jsx, src/components/SignInForm.jsx
Changed URL routing to look for case of the parameter passed in.
=> Added check for case for URL routing

src/components/ServiceRequestForm.jsx, src/utilities/FormHelpers.js
Dummies ID's were not returning in the routing because we were checking for numbers only. Now everything is a string so dummy ID's and real ids route properly
=> Had to change category ID to string to handle ID like D000005

src/css/modal-styles.css, src/utilities/config.js, src/utilities/returnEnvironmentItems.js
Added Staging environment variables and production variables. Also added the modal-styles.css to source. This will eventually need to be merged into either the master css file or the App.css file in this project but for now its just in source under the css folder and must be moved up separate from the other css files.
=> Add stage environment

src/utilities/config.js, src/utilities/returnEnvironmentItems.js
Fixed File locations during prod move.
=> Fixed file locations

src/components/ProvideDetails.jsx, src/components/ServiceRequestForm.jsx, src/services/authService.js, src/utilities/config.js, src/utilities/returnEnvironmentItems.js
Consolidated all the environment checks into one function. Updated all pages with new check and parameters. Ignore the name of the branch. This is NOT A HOT FIX!!!
=> Refactored environment check

src/components/ResetPasswordForm.jsx, src/components/SignInForm.jsx, src/components/SignUpForm.jsx
Fixing #142. Adds a check to reset the Password message after an attempted login. This will then trigger the bad password/username message. Also converted the signin, signup and password reset to use the SetFieldValues helper function.
=> Fix sign in error

src/components/IssueType.jsx, src/components/ResetPasswordForm.jsx, src/components/ServiceRequestForm.jsx, src/components/SignInForm.jsx, src/components/SignUpForm.jsx
Addresses #128. This fixes error styles for signup form. Converted ServiceRequest inputs to SeButtons for consistency. Removed default parameters from SeButton Component calls
=> Sign up form styles

src/components/ProvideDetails.jsx
fix issue with caption on addresses
=> Format autocomplete addressess in title case, instead of all caps

src/utilities/FormHelpers.js
Had to change the ID we were passing into a string. This was originally an int and therefore nothing was matching.
=> Url routing broken

package-lock.json, package.json, src/components/Alert.jsx, src/components/ResetPasswordForm.jsx, src/components/SignInForm.jsx, src/components/SignUpForm.jsx, src/components/withFormik.jsx, src/utilities/AlertHelper.jsx, src/utilities/AlertHelpers.js, src/utilities/CitysourcedResponseHelpers.js
=> Handle errors for server failures#136

src/components/Collaspe.jsx, src/components/ProvideDetails.jsx, src/components/map.jsx
=> removed pin on the map for default address

src/components/ProvideDetails.jsx
remove default value of latitude, longitude from withformik
=> remove default value of latitude, longitude from withformik

src/components/map.jsx
Added bin bounce effect on map
=> fix bin bounce effect on map#176

src/components/AutocompleteTypeField.jsx
=> fix bad import

src/components/Collapse.jsx, src/components/FormContainer.jsx, src/components/IssueType.jsx, src/css/Autocomplete.css
- Ensures top is not set with react, will also use auto which positions it where it should be
- Position search icon inside text box
- Adds Fieldset
- Align map and map toggle button center like production
=> Fix autocomplete

src/components/animalBreedType.jsx, src/components/animalColorType.jsx, src/components/otherAnimalTypes.jsx, src/components/petType.jsx, src/components/requestCategory.jsx, src/components/requestSubCategory.jsx, src/components/sexType.jsx
selected item on a combo box was not working when returning to previous page .
=> Update beta visual select

src/components/AdditionalInformation.jsx, src/components/AutocompleteTypeField.jsx, src/components/IssueType.jsx, src/components/describeTheProblem.jsx, src/components/requestCategory.jsx
Converts the text boxes to Text Inputs from the component library.
=> Update text input

src/components/GetReport.jsx, src/components/Note.jsx, src/components/ProvideDetails.jsx, src/components/ReportStatus.jsx, src/components/ServiceRequestForm.jsx, src/utilities/AlertHelpers.js
Added updates to messages per Web Services request.
=> Added updated messaging

src/App.css, src/components/SignInForm.jsx, src/components/SignUpForm.jsx
Adds CSS to make the eye icon in the password input text box appear.
=> Password Icon

public/data/categories.json, src/components/SeButton.jsx
Removed the click event for buttons that are disabled
=> Buttons no longer have event if disabled

src/components/ProvideDetails.jsx
Bug references here:
https://oittfs.bcg.ad.bcgov.us/BAUCollection/BaltimoreCounty.Gov%20Website/_workitems/edit/17647
=> Changed warning alert to info alert

src/utilities/config.js
pointing address lookup api to prod . test api was not working. Tim asked to do this
=> pointing address lookup to prod

public/data/prod/categories.json, src/utilities/returnEnvironmentItems.js
Copied most recent version of the prod file back into source
=> Update to production file

src/utilities/FormHelpers.js
URL parameter had out of order logic
=> Logic was out of order

src/utilities/FormHelpers.js
Had an extra closing bracket which thru off the entire function.
=> Fixed a compilation error

public/data/staging/categories.json, src/components/ServiceRequestForm.jsx
Hide form for some of the pets and animal if they have "shouldDisableForm:True"
=> fix pets disable form

public/data/prod/form-field-names.json, public/data/staging/categories.json, public/data/staging/form-field-names.json, public/data/staging/trash-recycling.json, src/components/ServiceRequestForm.jsx, src/components/TrashRecycleIssues.jsx, src/components/requestSubCategory.jsx, src/components/withFormik.jsx, src/utilities/FormHelpers.js, src/utilities/config.js
added new categories for trash and recyle
=> Add new request type for trash recycling

src/components/TrashRecycleIssues.jsx, src/components/requestCategory.jsx, src/components/requestSubCategory.jsx
Reverts baltimorecounty/react-baltcogo#238
=> Revert "Add new request type for trash recycling"
